version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    volumes:
      - ./src:/var/www/html/
    image: phpmyadmin/phpmyadmin
    build:
        context: ./src
        dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
    links:
      - "db"
  db:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: csym019
      MYSQL_ROOT_PASSWORD: csym019
      MYSQL_DATABASE: recipe_db
    restart: "on-failure"

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - "db"

